/* ============================================================
   CCAT Practice — Verbal + Math & Logic question bank
   Each item: { id, category, type, stem, options[], answer(index), explanation }
   Spatial questions are generated separately in spatial.js
   ============================================================ */
(function () {
  const V = "Verbal Reasoning";
  const M = "Math & Logic";

  const BANK = [
    /* ---------------- VERBAL: SYNONYMS ---------------- */
    { id: "v-syn-1", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>ABUNDANT</strong>",
      options: ["Scarce", "Plentiful", "Hollow", "Brief", "Sturdy"], answer: 1,
      explanation: "“Abundant” means existing in large quantities. “Plentiful” is the closest synonym." },
    { id: "v-syn-2", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>CANDID</strong>",
      options: ["Sweet", "Honest", "Hidden", "Rude", "Calm"], answer: 1,
      explanation: "“Candid” means frank and truthful, so “honest” is the best match." },
    { id: "v-syn-3", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>METICULOUS</strong>",
      options: ["Careless", "Thorough", "Lazy", "Hasty", "Loud"], answer: 1,
      explanation: "“Meticulous” means showing great attention to detail — i.e., thorough." },
    { id: "v-syn-4", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>BENEVOLENT</strong>",
      options: ["Cruel", "Kind", "Wealthy", "Strict", "Silent"], answer: 1,
      explanation: "“Benevolent” means well-meaning and kindly." },
    { id: "v-syn-5", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>OBSOLETE</strong>",
      options: ["Modern", "Outdated", "Useful", "Rare", "Heavy"], answer: 1,
      explanation: "“Obsolete” means no longer in use or out of date — “outdated.”" },
    { id: "v-syn-6", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>PRUDENT</strong>",
      options: ["Reckless", "Cautious", "Generous", "Hostile", "Tardy"], answer: 1,
      explanation: "“Prudent” means acting with care and good judgment — “cautious.”" },
    { id: "v-syn-7", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>LUCID</strong>",
      options: ["Confusing", "Clear", "Dim", "Dishonest", "Tense"], answer: 1,
      explanation: "“Lucid” means expressed clearly and easy to understand." },
    { id: "v-syn-8", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>TENACIOUS</strong>",
      options: ["Weak", "Persistent", "Gentle", "Brief", "Hollow"], answer: 1,
      explanation: "“Tenacious” means holding firmly to a purpose — “persistent.”" },
    { id: "v-syn-9", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>FRUGAL</strong>",
      options: ["Wasteful", "Thrifty", "Wealthy", "Greedy", "Honest"], answer: 1,
      explanation: "“Frugal” means careful with money — “thrifty.”" },
    { id: "v-syn-10", category: V, type: "Synonym",
      stem: "Select the word that is most <strong>similar</strong> in meaning to:<br><strong>AMPLE</strong>",
      options: ["Insufficient", "Sufficient", "Tiny", "Sharp", "Empty"], answer: 1,
      explanation: "“Ample” means enough or more than enough — “sufficient.”" },

    /* ---------------- VERBAL: ANTONYMS ---------------- */
    { id: "v-ant-1", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>GENEROUS</strong>",
      options: ["Giving", "Stingy", "Kind", "Wealthy", "Honest"], answer: 1,
      explanation: "“Generous” means free in giving; its opposite is “stingy.”" },
    { id: "v-ant-2", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>TRANSPARENT</strong>",
      options: ["Clear", "Opaque", "Bright", "Thin", "Visible"], answer: 1,
      explanation: "“Transparent” lets light through; “opaque” does not — they are opposites." },
    { id: "v-ant-3", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>EXPAND</strong>",
      options: ["Grow", "Contract", "Stretch", "Inflate", "Widen"], answer: 1,
      explanation: "“Expand” means to grow larger; “contract” means to shrink." },
    { id: "v-ant-4", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>PRAISE</strong>",
      options: ["Compliment", "Criticize", "Honor", "Admire", "Applaud"], answer: 1,
      explanation: "To “praise” is to express approval; to “criticize” is to express disapproval." },
    { id: "v-ant-5", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>ANCIENT</strong>",
      options: ["Old", "Modern", "Antique", "Aged", "Historic"], answer: 1,
      explanation: "“Ancient” means very old; its opposite is “modern.”" },
    { id: "v-ant-6", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>HUMBLE</strong>",
      options: ["Modest", "Arrogant", "Shy", "Quiet", "Plain"], answer: 1,
      explanation: "“Humble” means modest; its opposite is “arrogant.”" },
    { id: "v-ant-7", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>ACCELERATE</strong>",
      options: ["Hasten", "Decelerate", "Speed", "Rush", "Advance"], answer: 1,
      explanation: "“Accelerate” means to speed up; “decelerate” means to slow down." },
    { id: "v-ant-8", category: V, type: "Antonym",
      stem: "Select the word that is most <strong>opposite</strong> in meaning to:<br><strong>FERTILE</strong>",
      options: ["Productive", "Barren", "Rich", "Lush", "Fruitful"], answer: 1,
      explanation: "“Fertile” land produces abundantly; “barren” land produces nothing." },

    /* ---------------- VERBAL: ANALOGIES ---------------- */
    { id: "v-ana-1", category: V, type: "Analogy",
      stem: "<strong>Puppy</strong> is to <strong>Dog</strong> as <strong>Kitten</strong> is to ___",
      options: ["Cat", "Mouse", "Lion", "Pup", "Kennel"], answer: 0,
      explanation: "A puppy is a young dog; a kitten is a young cat." },
    { id: "v-ana-2", category: V, type: "Analogy",
      stem: "<strong>Author</strong> is to <strong>Book</strong> as <strong>Composer</strong> is to ___",
      options: ["Painting", "Symphony", "Stage", "Audience", "Piano"], answer: 1,
      explanation: "An author creates a book; a composer creates a symphony (a musical work)." },
    { id: "v-ana-3", category: V, type: "Analogy",
      stem: "<strong>Hot</strong> is to <strong>Cold</strong> as <strong>Up</strong> is to ___",
      options: ["Down", "High", "Left", "Over", "Top"], answer: 0,
      explanation: "Hot and cold are opposites, as are up and down." },
    { id: "v-ana-4", category: V, type: "Analogy",
      stem: "<strong>Glove</strong> is to <strong>Hand</strong> as <strong>Sock</strong> is to ___",
      options: ["Shoe", "Foot", "Toe", "Leg", "Arm"], answer: 1,
      explanation: "A glove is worn on the hand; a sock is worn on the foot." },
    { id: "v-ana-5", category: V, type: "Analogy",
      stem: "<strong>Fish</strong> is to <strong>School</strong> as <strong>Wolf</strong> is to ___",
      options: ["Herd", "Pack", "Flock", "Swarm", "Pride"], answer: 1,
      explanation: "A group of fish is a school; a group of wolves is a pack." },
    { id: "v-ana-6", category: V, type: "Analogy",
      stem: "<strong>Thermometer</strong> is to <strong>Temperature</strong> as <strong>Clock</strong> is to ___",
      options: ["Hours", "Time", "Speed", "Weight", "Pressure"], answer: 1,
      explanation: "A thermometer measures temperature; a clock measures time." },
    { id: "v-ana-7", category: V, type: "Analogy",
      stem: "<strong>Library</strong> is to <strong>Books</strong> as <strong>Gallery</strong> is to ___",
      options: ["Paintings", "Movies", "Plays", "Cars", "Tools"], answer: 0,
      explanation: "A library holds books; a (art) gallery holds paintings." },
    { id: "v-ana-8", category: V, type: "Analogy",
      stem: "<strong>Doctor</strong> is to <strong>Patient</strong> as <strong>Lawyer</strong> is to ___",
      options: ["Judge", "Client", "Court", "Law", "Jury"], answer: 1,
      explanation: "A doctor serves a patient; a lawyer serves a client." },
    { id: "v-ana-9", category: V, type: "Analogy",
      stem: "<strong>Bee</strong> is to <strong>Hive</strong> as <strong>Bird</strong> is to ___",
      options: ["Cage", "Nest", "Tree", "Sky", "Egg"], answer: 1,
      explanation: "A bee lives in a hive; a bird lives in a nest." },
    { id: "v-ana-10", category: V, type: "Analogy",
      stem: "<strong>Calm</strong> is to <strong>Panic</strong> as <strong>Brave</strong> is to ___",
      options: ["Bold", "Cowardly", "Strong", "Fearless", "Heroic"], answer: 1,
      explanation: "Calm is the opposite of panic; brave is the opposite of cowardly." },
    { id: "v-ana-11", category: V, type: "Analogy",
      stem: "<strong>Pen</strong> is to <strong>Write</strong> as <strong>Scissors</strong> is to ___",
      options: ["Sharp", "Cut", "Paper", "Metal", "Sew"], answer: 1,
      explanation: "A pen is used to write; scissors are used to cut." },
    { id: "v-ana-12", category: V, type: "Analogy",
      stem: "<strong>Mile</strong> is to <strong>Distance</strong> as <strong>Pound</strong> is to ___",
      options: ["Length", "Weight", "Time", "Volume", "Speed"], answer: 1,
      explanation: "A mile is a unit of distance; a pound is a unit of weight." },

    /* ---------------- VERBAL: SENTENCE COMPLETION ---------------- */
    { id: "v-sen-1", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“Although the instructions seemed simple, the process turned out to be far more ___ than anyone expected.”",
      options: ["straightforward", "complicated", "brief", "pleasant", "boring"], answer: 1,
      explanation: "“Although ... simple” signals a contrast, so the process must be the opposite — complicated." },
    { id: "v-sen-2", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“The scientist's ___ approach meant she double-checked every measurement before drawing a conclusion.”",
      options: ["careless", "meticulous", "hasty", "reckless", "indifferent"], answer: 1,
      explanation: "Double-checking every measurement describes a careful, “meticulous” approach." },
    { id: "v-sen-3", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“Despite the team's ___ effort, they fell just short of winning the championship.”",
      options: ["lazy", "valiant", "half-hearted", "reluctant", "minimal"], answer: 1,
      explanation: "“Despite ... fell just short” implies they tried hard — a “valiant” (brave, determined) effort." },
    { id: "v-sen-4", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“The new policy was so ___ that even longtime employees struggled to understand it.”",
      options: ["clear", "convoluted", "simple", "obvious", "plain"], answer: 1,
      explanation: "If people struggle to understand it, the policy is “convoluted” (overly complex)." },
    { id: "v-sen-5", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“Her argument was ___; every point followed logically from the one before it.”",
      options: ["confusing", "coherent", "weak", "random", "vague"], answer: 1,
      explanation: "Points following logically describe a “coherent” argument." },
    { id: "v-sen-6", category: V, type: "Sentence Completion",
      stem: "Choose the word that best completes the sentence:<br>“Because the evidence was ___, the jury could not reach a unanimous verdict.”",
      options: ["conclusive", "inconclusive", "obvious", "overwhelming", "clear"], answer: 1,
      explanation: "Failing to reach a verdict implies the evidence was “inconclusive.”" },

    /* ---------------- VERBAL: ODD ONE OUT ---------------- */
    { id: "v-odd-1", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Rose", "Tulip", "Daisy", "Oak", "Lily"], answer: 3,
      explanation: "Rose, tulip, daisy and lily are flowers; an oak is a tree." },
    { id: "v-odd-2", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Copper", "Iron", "Gold", "Diamond", "Silver"], answer: 3,
      explanation: "Copper, iron, gold and silver are metals; a diamond is a gemstone." },
    { id: "v-odd-3", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Square", "Triangle", "Circle", "Cube", "Hexagon"], answer: 3,
      explanation: "Square, triangle, circle and hexagon are 2-D shapes; a cube is 3-D." },
    { id: "v-odd-4", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Apple", "Banana", "Carrot", "Mango", "Cherry"], answer: 2,
      explanation: "Apple, banana, mango and cherry are fruits; a carrot is a vegetable." },
    { id: "v-odd-5", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Violin", "Cello", "Flute", "Guitar", "Harp"], answer: 2,
      explanation: "Violin, cello, guitar and harp are string instruments; a flute is a wind instrument." },
    { id: "v-odd-6", category: V, type: "Odd One Out",
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Mercury", "Venus", "Mars", "Moon", "Jupiter"], answer: 3,
      explanation: "Mercury, Venus, Mars and Jupiter are planets; the Moon is a satellite." },

    /* ---------------- MATH: ARITHMETIC / WORD PROBLEMS ---------------- */
    { id: "m-ar-1", category: M, type: "Word Problem",
      stem: "A shirt originally priced at <strong>$40</strong> is on sale for <strong>25% off</strong>. What is the sale price?",
      options: ["$10", "$25", "$30", "$32", "$35"], answer: 2,
      explanation: "25% of $40 is $10, so the sale price is $40 − $10 = $30." },
    { id: "m-ar-2", category: M, type: "Word Problem",
      stem: "If <strong>3 pencils</strong> cost <strong>$1.20</strong>, how much do <strong>7 pencils</strong> cost at the same rate?",
      options: ["$2.40", "$2.80", "$3.00", "$3.20", "$2.10"], answer: 1,
      explanation: "Each pencil is $1.20 ÷ 3 = $0.40, so 7 × $0.40 = $2.80." },
    { id: "m-ar-3", category: M, type: "Word Problem",
      stem: "A car travels <strong>150 miles in 3 hours</strong>. At that rate, how far will it travel in <strong>5 hours</strong>?",
      options: ["200 miles", "225 miles", "250 miles", "300 miles", "450 miles"], answer: 2,
      explanation: "Speed = 150 ÷ 3 = 50 mph, so 50 × 5 = 250 miles." },
    { id: "m-ar-4", category: M, type: "Percentages",
      stem: "What is <strong>15% of 240</strong>?",
      options: ["24", "36", "40", "48", "360"], answer: 1,
      explanation: "10% of 240 is 24 and 5% is 12, so 15% = 24 + 12 = 36." },
    { id: "m-ar-5", category: M, type: "Percentages",
      stem: "A team won <strong>18 of its 24 games</strong>. What percentage did it win?",
      options: ["60%", "66%", "70%", "75%", "80%"], answer: 3,
      explanation: "18 ÷ 24 = 0.75 = 75%." },
    { id: "m-ar-6", category: M, type: "Word Problem",
      stem: "The sum of three <strong>consecutive integers</strong> is <strong>72</strong>. What is the largest of the three?",
      options: ["23", "24", "25", "26", "27"], answer: 2,
      explanation: "The middle integer is 72 ÷ 3 = 24, so the integers are 23, 24, 25 — the largest is 25." },
    { id: "m-ar-7", category: M, type: "Algebra",
      stem: "If a number increased by <strong>20%</strong> equals <strong>90</strong>, what is the number?",
      options: ["70", "72", "75", "78", "108"], answer: 2,
      explanation: "x × 1.20 = 90, so x = 90 ÷ 1.2 = 75." },
    { id: "m-ar-8", category: M, type: "Ratios",
      stem: "A recipe needs <strong>2 cups of flour for 12 cookies</strong>. How many cups are needed for <strong>30 cookies</strong>?",
      options: ["4", "4.5", "5", "5.5", "6"], answer: 2,
      explanation: "2 cups ÷ 12 = 1/6 cup per cookie, so 30 × 1/6 = 5 cups." },
    { id: "m-ar-9", category: M, type: "Word Problem",
      stem: "Tom is <strong>twice as old</strong> as Jerry. In <strong>5 years</strong>, the sum of their ages will be <strong>40</strong>. How old is Tom now?",
      options: ["15", "18", "20", "24", "30"], answer: 2,
      explanation: "Let Jerry = j and Tom = 2j. (j+5)+(2j+5)=40 → 3j=30 → j=10, so Tom = 20." },
    { id: "m-ar-10", category: M, type: "Word Problem",
      stem: "A worker earns <strong>$18 per hour</strong> and works <strong>7.5 hours</strong>. How much does she earn?",
      options: ["$120", "$126", "$135", "$144", "$150"], answer: 2,
      explanation: "$18 × 7.5 = $135." },
    { id: "m-ar-11", category: M, type: "Logic Puzzle",
      stem: "If <strong>5 machines</strong> make <strong>5 widgets</strong> in <strong>5 minutes</strong>, how long would <strong>100 machines</strong> take to make <strong>100 widgets</strong>?",
      options: ["5 minutes", "20 minutes", "50 minutes", "100 minutes", "500 minutes"], answer: 0,
      explanation: "Each machine makes 1 widget every 5 minutes. 100 machines make 100 widgets in the same 5 minutes." },
    { id: "m-ar-12", category: M, type: "Geometry",
      stem: "A rectangle has length <strong>12</strong> and width <strong>5</strong>. What is its <strong>area</strong>?",
      options: ["17", "34", "60", "120", "50"], answer: 2,
      explanation: "Area = length × width = 12 × 5 = 60." },
    { id: "m-ar-13", category: M, type: "Geometry",
      stem: "A square has an <strong>area of 49</strong>. What is its <strong>perimeter</strong>?",
      options: ["14", "21", "28", "49", "56"], answer: 2,
      explanation: "Side = √49 = 7, so perimeter = 4 × 7 = 28." },
    { id: "m-ar-14", category: M, type: "Percentages",
      stem: "A store buys an item for <strong>$80</strong> and sells it for <strong>$100</strong>. What is the percent <strong>markup</strong>?",
      options: ["15%", "20%", "25%", "30%", "80%"], answer: 2,
      explanation: "Markup = $20 increase ÷ $80 cost = 0.25 = 25%." },
    { id: "m-ar-15", category: M, type: "Algebra",
      stem: "If <strong>x + 7 = 3x − 5</strong>, what is the value of <strong>x</strong>?",
      options: ["4", "5", "6", "7", "12"], answer: 2,
      explanation: "x + 7 = 3x − 5 → 12 = 2x → x = 6." },
    { id: "m-ar-16", category: M, type: "Algebra",
      stem: "Half of a number is <strong>8 more</strong> than a third of the same number. What is the number?",
      options: ["24", "36", "48", "54", "96"], answer: 2,
      explanation: "x/2 = x/3 + 8 → x/6 = 8 → x = 48." },
    { id: "m-ar-17", category: M, type: "Percentages",
      stem: "A jacket is discounted <strong>30%</strong>, then an additional <strong>10% off the sale price</strong>. What is the total percent off the original price?",
      options: ["40%", "37%", "33%", "27%", "21%"], answer: 1,
      explanation: "0.70 × 0.90 = 0.63 of the original price is paid, so 37% is off." },
    { id: "m-ar-18", category: M, type: "Ratios",
      stem: "On a map, <strong>1 inch = 50 miles</strong>. How many miles does <strong>3.5 inches</strong> represent?",
      options: ["150", "165", "175", "200", "350"], answer: 2,
      explanation: "3.5 × 50 = 175 miles." },
    { id: "m-ar-19", category: M, type: "Fractions",
      stem: "A tank holds <strong>240 liters</strong> and is currently <strong>5/8 full</strong>. How many liters are in it?",
      options: ["96", "120", "150", "180", "200"], answer: 2,
      explanation: "240 × 5/8 = 150 liters." },
    { id: "m-ar-20", category: M, type: "Percentages",
      stem: "<strong>12</strong> is what percent of <strong>48</strong>?",
      options: ["20%", "24%", "25%", "30%", "40%"], answer: 2,
      explanation: "12 ÷ 48 = 0.25 = 25%." },
    { id: "m-ar-21", category: M, type: "Ratios",
      stem: "The ratio of boys to girls in a class is <strong>3 : 2</strong> and there are <strong>30 students</strong>. How many girls are there?",
      options: ["10", "12", "15", "18", "20"], answer: 1,
      explanation: "The ratio has 5 parts; each part = 30 ÷ 5 = 6. Girls = 2 parts = 12." },
    { id: "m-ar-22", category: M, type: "Percentages",
      stem: "A bicycle's price rose from <strong>$200 to $250</strong>. What is the percent increase?",
      options: ["20%", "25%", "30%", "40%", "50%"], answer: 1,
      explanation: "Increase = $50 ÷ $200 = 0.25 = 25%." },
    { id: "m-ar-23", category: M, type: "Averages",
      stem: "What is the <strong>average</strong> of 14, 18, 22, and 26?",
      options: ["18", "20", "21", "22", "24"], answer: 1,
      explanation: "Sum = 80; 80 ÷ 4 = 20." },
    { id: "m-ar-24", category: M, type: "Logic Puzzle",
      stem: "If <strong>8 workers</strong> can build a wall in <strong>6 days</strong>, how many days would <strong>4 workers</strong> take at the same rate?",
      options: ["3", "8", "10", "12", "24"], answer: 3,
      explanation: "The job is 8 × 6 = 48 worker-days. With 4 workers: 48 ÷ 4 = 12 days." },

    /* ---------------- MATH: NUMBER SERIES ---------------- */
    { id: "m-ser-1", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>2, 4, 8, 16, ?</strong>",
      options: ["18", "24", "30", "32", "64"], answer: 3,
      explanation: "Each term doubles: 16 × 2 = 32." },
    { id: "m-ser-2", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>3, 6, 9, 12, ?</strong>",
      options: ["13", "14", "15", "16", "18"], answer: 2,
      explanation: "Add 3 each time: 12 + 3 = 15." },
    { id: "m-ser-3", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>1, 4, 9, 16, ?</strong>",
      options: ["20", "23", "24", "25", "36"], answer: 3,
      explanation: "These are perfect squares (1², 2², 3², 4²); next is 5² = 25." },
    { id: "m-ser-4", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>81, 27, 9, 3, ?</strong>",
      options: ["0", "1", "2", "3", "6"], answer: 1,
      explanation: "Each term is divided by 3: 3 ÷ 3 = 1." },
    { id: "m-ser-5", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>1, 1, 2, 3, 5, 8, ?</strong>",
      options: ["11", "12", "13", "15", "21"], answer: 2,
      explanation: "Fibonacci: each term is the sum of the previous two; 5 + 8 = 13." },
    { id: "m-ser-6", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>2, 5, 11, 23, ?</strong>",
      options: ["35", "41", "46", "47", "48"], answer: 3,
      explanation: "Each term is doubled and increased by 1: 23 × 2 + 1 = 47." },
    { id: "m-ser-7", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>100, 96, 88, 76, 60, ?</strong>",
      options: ["36", "40", "44", "48", "52"], answer: 1,
      explanation: "Differences grow by 4 (−4, −8, −12, −16, −20): 60 − 20 = 40." },
    { id: "m-ser-8", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>5, 10, 8, 16, 14, 28, ?</strong>",
      options: ["24", "26", "30", "42", "56"], answer: 1,
      explanation: "The pattern alternates ×2 then −2: 28 − 2 = 26." },
    { id: "m-ser-9", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>7, 14, 28, 56, ?</strong>",
      options: ["84", "96", "102", "112", "120"], answer: 3,
      explanation: "Each term doubles: 56 × 2 = 112." },
    { id: "m-ser-10", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>2, 3, 5, 8, 12, 17, ?</strong>",
      options: ["21", "22", "23", "24", "25"], answer: 2,
      explanation: "Differences increase by 1 (+1, +2, +3, +4, +5): 17 + 6 = 23." },
    { id: "m-ser-11", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>64, 32, 16, 8, ?</strong>",
      options: ["2", "4", "6", "8", "0"], answer: 1,
      explanation: "Each term is halved: 8 ÷ 2 = 4." },
    { id: "m-ser-12", category: M, type: "Number Series",
      stem: "What number comes next?<br><strong>3, 7, 15, 31, ?</strong>",
      options: ["47", "55", "62", "63", "64"], answer: 3,
      explanation: "Each term is doubled and increased by 1: 31 × 2 + 1 = 63." },

    /* ---------------- LOGIC / DEDUCTION ---------------- */
    { id: "m-log-1", category: M, type: "Logical Reasoning",
      stem: "All roses are flowers. Some flowers fade quickly. Which statement <strong>must</strong> be true?",
      options: ["All roses fade quickly.", "Some flowers are roses.", "All flowers are roses.", "Some roses fade quickly.", "No roses fade quickly."], answer: 1,
      explanation: "Since every rose is a flower, roses are flowers — so some flowers are roses. The fading flowers might not be the roses, so the other options aren't guaranteed." },
    { id: "m-log-2", category: M, type: "Logical Reasoning",
      stem: "If it rains, the match is cancelled. The match was <strong>not</strong> cancelled. Therefore:",
      options: ["It rained.", "It did not rain.", "The match was postponed.", "It will rain tomorrow.", "Cannot be determined."], answer: 1,
      explanation: "Rain would force a cancellation. Since there was no cancellation, it could not have rained." },
    { id: "m-log-3", category: M, type: "Logical Reasoning",
      stem: "Every student in the class passed the exam. John is a student in the class. Therefore:",
      options: ["John failed the exam.", "John passed the exam.", "John was absent.", "Some students failed.", "Cannot be determined."], answer: 1,
      explanation: "If every student passed and John is a student in that class, John passed." },
    { id: "m-log-4", category: M, type: "Logical Reasoning",
      stem: "Mark is taller than Sara. Sara is taller than Tom. Who is the <strong>shortest</strong>?",
      options: ["Mark", "Sara", "Tom", "Cannot tell", "All are equal"], answer: 2,
      explanation: "Mark > Sara > Tom in height, so Tom is the shortest." },
    { id: "m-log-5", category: M, type: "Logical Reasoning",
      stem: "In a race, Anna finished ahead of Beth but behind Carol. Who finished <strong>first</strong> among the three?",
      options: ["Anna", "Beth", "Carol", "Cannot tell", "A tie"], answer: 2,
      explanation: "Carol is ahead of Anna, and Anna is ahead of Beth, so the order is Carol, Anna, Beth — Carol is first." },
    { id: "m-log-6", category: M, type: "Logical Reasoning",
      stem: "Some musicians are painters. All painters are creative. Which statement <strong>must</strong> be true?",
      options: ["All musicians are creative.", "Some musicians are creative.", "All creative people are painters.", "No musicians are creative.", "Some painters are not creative."], answer: 1,
      explanation: "The musicians who are painters must be creative (since all painters are), so some musicians are creative." },
    { id: "m-log-7", category: M, type: "Logical Reasoning",
      stem: "If today is <strong>three days after Monday</strong>, what day is <strong>tomorrow</strong>?",
      options: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], answer: 2,
      explanation: "Three days after Monday is Thursday, so tomorrow is Friday." },
    { id: "m-log-8", category: M, type: "Logical Reasoning",
      stem: "A is directly north of B. C is directly south of B. Which point is <strong>farthest north</strong>?",
      options: ["A", "B", "C", "Cannot tell", "B and C tie"], answer: 0,
      explanation: "B is north of C, and A is north of B, so A is the farthest north." }
  ];

  /* ---------------- HARDER ITEMS (difficulty 3) ---------------- */
  const HARD = [
    // Hard synonyms
    { id: "v-syn-h1", category: V, type: "Synonym", difficulty: 3,
      stem: "Select the word most <strong>similar</strong> in meaning to:<br><strong>EPHEMERAL</strong>",
      options: ["Eternal", "Fleeting", "Solid", "Joyful", "Massive"], answer: 1,
      explanation: "“Ephemeral” means lasting a very short time — “fleeting.”" },
    { id: "v-syn-h2", category: V, type: "Synonym", difficulty: 3,
      stem: "Select the word most <strong>similar</strong> in meaning to:<br><strong>UBIQUITOUS</strong>",
      options: ["Rare", "Widespread", "Hidden", "Unique", "Tiny"], answer: 1,
      explanation: "“Ubiquitous” means present everywhere — “widespread.”" },
    { id: "v-syn-h3", category: V, type: "Synonym", difficulty: 3,
      stem: "Select the word most <strong>similar</strong> in meaning to:<br><strong>GARRULOUS</strong>",
      options: ["Silent", "Talkative", "Angry", "Lazy", "Generous"], answer: 1,
      explanation: "“Garrulous” means excessively talkative." },
    { id: "v-syn-h4", category: V, type: "Synonym", difficulty: 3,
      stem: "Select the word most <strong>similar</strong> in meaning to:<br><strong>AMELIORATE</strong>",
      options: ["Worsen", "Improve", "Ignore", "Confuse", "Delay"], answer: 1,
      explanation: "“Ameliorate” means to make better — “improve.”" },
    { id: "v-syn-h5", category: V, type: "Synonym", difficulty: 3,
      stem: "Select the word most <strong>similar</strong> in meaning to:<br><strong>INSIPID</strong>",
      options: ["Spicy", "Bland", "Bright", "Loud", "Sharp"], answer: 1,
      explanation: "“Insipid” means lacking flavour or interest — “bland.”" },
    // Hard antonyms
    { id: "v-ant-h1", category: V, type: "Antonym", difficulty: 3,
      stem: "Select the word most <strong>opposite</strong> in meaning to:<br><strong>CANDID</strong>",
      options: ["Frank", "Evasive", "Honest", "Open", "Direct"], answer: 1,
      explanation: "“Candid” means open and honest; “evasive” means avoiding the truth." },
    { id: "v-ant-h2", category: V, type: "Antonym", difficulty: 3,
      stem: "Select the word most <strong>opposite</strong> in meaning to:<br><strong>AUSTERE</strong>",
      options: ["Plain", "Lavish", "Strict", "Harsh", "Simple"], answer: 1,
      explanation: "“Austere” means severe or plain; “lavish” means luxurious and abundant." },
    { id: "v-ant-h3", category: V, type: "Antonym", difficulty: 3,
      stem: "Select the word most <strong>opposite</strong> in meaning to:<br><strong>TRANSIENT</strong>",
      options: ["Brief", "Permanent", "Fleeting", "Temporary", "Passing"], answer: 1,
      explanation: "“Transient” means lasting only briefly; its opposite is “permanent.”" },
    { id: "v-ant-h4", category: V, type: "Antonym", difficulty: 3,
      stem: "Select the word most <strong>opposite</strong> in meaning to:<br><strong>MITIGATE</strong>",
      options: ["Ease", "Aggravate", "Lessen", "Soften", "Reduce"], answer: 1,
      explanation: "“Mitigate” means to make less severe; “aggravate” means to make worse." },
    // Hard analogies
    { id: "v-ana-h1", category: V, type: "Analogy", difficulty: 3,
      stem: "<strong>Cartographer</strong> is to <strong>Maps</strong> as <strong>Choreographer</strong> is to ___",
      options: ["Songs", "Dances", "Plays", "Maps", "Poems"], answer: 1,
      explanation: "A cartographer creates maps; a choreographer creates dances." },
    { id: "v-ana-h2", category: V, type: "Analogy", difficulty: 3,
      stem: "<strong>Drought</strong> is to <strong>Water</strong> as <strong>Famine</strong> is to ___",
      options: ["Rain", "Food", "Land", "Heat", "Money"], answer: 1,
      explanation: "A drought is a shortage of water; a famine is a shortage of food." },
    { id: "v-ana-h3", category: V, type: "Analogy", difficulty: 3,
      stem: "<strong>Whisper</strong> is to <strong>Shout</strong> as <strong>Trickle</strong> is to ___",
      options: ["Drip", "Flood", "Leak", "Splash", "Drop"], answer: 1,
      explanation: "A whisper is a faint version of a shout; a trickle is a faint version of a flood." },
    // Hard sentence completion
    { id: "v-sen-h1", category: V, type: "Sentence Completion", difficulty: 3,
      stem: "Choose the word that best completes the sentence:<br>“The senator's ___ remarks, though eloquent, ultimately revealed nothing of her actual position.”",
      options: ["candid", "evasive", "blunt", "honest", "decisive"], answer: 1,
      explanation: "Revealing nothing of her position means the remarks were “evasive,” despite being eloquent." },
    { id: "v-sen-h2", category: V, type: "Sentence Completion", difficulty: 3,
      stem: "Choose the word that best completes the sentence:<br>“Far from being ___, the critic's review was a scathing dismissal of the entire production.”",
      options: ["harsh", "laudatory", "negative", "cruel", "brief"], answer: 1,
      explanation: "“Far from being ___” signals a contrast with “scathing,” so the missing word means praising — “laudatory.”" },
    // Hard odd-one-out (concept grouping)
    { id: "v-odd-h1", category: V, type: "Odd One Out", difficulty: 2,
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Brisk", "Swift", "Rapid", "Sluggish", "Quick"], answer: 3,
      explanation: "Brisk, swift, rapid and quick all mean fast; “sluggish” means slow." },
    { id: "v-odd-h2", category: V, type: "Odd One Out", difficulty: 2,
      stem: "Which word does <strong>not</strong> belong with the others?",
      options: ["Joy", "Grief", "Sorrow", "Misery", "Despair"], answer: 0,
      explanation: "Grief, sorrow, misery and despair all relate to sadness; “joy” does not." },
    // Hard logic / syllogisms
    { id: "m-log-h1", category: M, type: "Logical Reasoning", difficulty: 3,
      stem: "All gleeks are florns. No florns are dops. Therefore:",
      options: ["All gleeks are dops.", "No gleeks are dops.", "Some dops are gleeks.", "All dops are florns.", "Cannot be determined."], answer: 1,
      explanation: "Every gleek is a florn, and no florn is a dop, so no gleek can be a dop." },
    { id: "m-log-h2", category: M, type: "Logical Reasoning", difficulty: 3,
      stem: "In a race of five runners: C beat D, A beat C, E beat A, and B beat E. Who finished <strong>first</strong>?",
      options: ["A", "B", "C", "D", "E"], answer: 1,
      explanation: "The order is B > E > A > C > D, so B finished first." },
    { id: "m-log-h3", category: M, type: "Logical Reasoning", difficulty: 3,
      stem: "Some artists are teachers. All teachers are employed. Which statement <strong>must</strong> be true?",
      options: ["All artists are employed.", "Some artists are employed.", "All employed people are teachers.", "No artists are employed.", "Some teachers are not employed."], answer: 1,
      explanation: "The artists who are teachers must be employed, so some artists are employed." }
  ];
  HARD.forEach((q) => BANK.push(q));

  // Default difficulty by type for any item not explicitly tagged.
  const DIFF_BY_TYPE = {
    "Synonym": 1, "Antonym": 1, "Analogy": 2, "Sentence Completion": 2, "Odd One Out": 1,
    "Word Problem": 2, "Percentages": 1, "Ratios": 2, "Algebra": 2, "Geometry": 1,
    "Averages": 1, "Fractions": 1, "Number Series": 2, "Logical Reasoning": 2, "Logic Puzzle": 3
  };
  BANK.forEach((q) => { if (q.difficulty == null) q.difficulty = DIFF_BY_TYPE[q.type] || 2; });

  window.QUESTION_BANK = BANK;
})();
